#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  3/9/2016                                          ###
#                                                            ###
# ##############################################################
'''


# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

# ---------------------------------------------------------------------
settings_fig = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAC5BJ"
    "REFUWIWVl2uUldV5x/97v7fznnNmzsyZM8ycuQIjlwEzSjEQETEk2qwEgeCliS689ENJKY1Z"
    "rRFLiEmMmtUV+yG21qTYWuulIRhLoyYKMl5gwIIgDDADc2OY6zlz7vf3ut+nHyDTUJKs5fNp"
    "v2vv9X9+6/88e797M3yK+ObeYXBhoWQJmI4LFUDFdBHQZSiqAi1Ug3/8SuunkYT8ux9ExAAQ"
    "Y+yqhVt/NQ4hbE5M8hzhfN203Rsqtpf2yFOWtIW2JcrUIGvqp0p+VRARiKiKiHyXxyAiPxHh"
    "kX0zOJcVMAXhh28PxntnSjSYs2j/cJpu2vFLDwt2fEmruhVEnwCN3wMAdBPh+RxdEp/3GDY8"
    "1/eHHXg9RmCMgYiKAOoAmJenKgBgmQV82O+g3BRU59YFpPY5ARQAmqfUMpmBAfCs4gGgtweB"
    "jgjKM9tw8ZyBs2PxSyqjT+CNp652aBbgfALYPSLw6P6LCKpIzw2qe0eS5eOxovVUtMYPw7Dw"
    "wqEYnnOoavu6BZGsTYhXiIUUUHM0zBDxL8AQ3r33mSFcv/Z2mKva8fa+o3sMm45d99ev/cNw"
    "LIfybwax+ofd6B+aQubl+wEA/LcAriNwZDiJiayBgKzsWjm35qubrmt80hbU/eL7A/q50QRG"
    "UxW0hrW1rSEfPGIo2S48zsWiljqgyv+ZO792CxYt6kQ6lr72xq6m1FfuWH734q65Txtl4/uH"
    "n7wdJy48Dl0xwLk368Bst2WJ2LQBeu/k5It3dDU80BRUAAAZy8MrPSPu/v7kw7dd13T/ivaa"
    "5QtaajBcEMibgjgDamWw/cfGMDCZfXMwhdNfX9Oys6krimMxAFkDxbExBIzMzrDOfrTvbBZn"
    "h6eQ3f2NKwHGPWKD0y719E28vGV1y+YGv4JJhxCQGFQAg/ESomE/uMIxXhQomh4qtoeKQ5Ak"
    "hpCuIZEowCMLSkc9Phx1kZy00exnSA70Y89rb0OcTi0NzjP65bbrkNuz7coe+IsXh2liJoMm"
    "zb6vUCx9fueGa1tkzhCveGCMIVwXpITlsXzJhWN7qLiCTIfBdj1UDMJYxmHhGh3UXO0d7LN4"
    "atpEnY+RnUiyYz0fg8vqGwvvXpmOT0/B4P7ZEsz2QNawcOvCEGSJ0DOQWPNqzygUAbhEKNoC"
    "kwWHZSsuHJdIcBm6X2eBKh/T/H7GucJqQhrMOQr1nK7w1GgZPhLwGQXv5KEjmIinRxxX+ttz"
    "aT4T1jT4nPLVAJ1BAcO28eAXO/FnazpHDw6lHzk7lQPnkihZHmyXyBIcjpBZPFXBwf8Zxr7u"
    "Phzs6UcsnoMVknFmxGHZMRMeQJzgJcYn+ejFiYItBR763LvfHkEpB1EpouBq2PTkgUsl2N6d"
    "g10poVrj0GQHX1sagUfA4/nSxmhtAHFDcMsjeIIxx+M49FEf9r55EJMz6WnXdo/5/Lq3eGHL"
    "za19C+sDkRZ4qg7PFawMLoKhiBSNNiYTH092j8vVaA4KGHYQG29ciL0Pr8E66QCk5XduhWkY"
    "aAjKODqcxPtnpvSeodTNXe21j4XrqxArCeYKIseTqPvgGfYvL+xFOpn9gVfdtBXhuc+7jrYn"
    "fn76aZc5ZmPYf2tVMICSy2C7xCRF9mRh1rnMtDb/if+g1NyJk7u2YEVvDK0HJ8EqRbAtr56C"
    "ELg75FcebqvzRRnnbY0hHxa21WLSlFAxXHhgGJ/K4Zlnd2N6KrcDpvn3UscSXNuggFU1IBSp"
    "w7yIhlgi/+r89ui9U24QRdOGIjFSPYM5+RQcOeAq5dQ0lYtj3Db/RmE4IRhBFq4H03bW3b+2"
    "Y2VkThBFk+AwhotFByVbwHZcyJLPOz8c44l0cRjV0X8PdDWjnMyjNyYgZ1O4q3M+ei9MwnLo"
    "6XnNzr06JyQsj0iVmM39YHXtgOvIhqK3MXeqLT5y4XjJQe2mx7flZHIckCtietCHaQ5kbIaK"
    "JUA20SU4gqoxUbFd7gpxGEQzUTOOdDiM7K474AIwVvdhYDwJwdXzqzsbQURwHWJCEgSSGHGZ"
    "uOYD+SB4MSm7HJiaLtc/u5jlZMvz4IE1pnIG2kNVqKkGHEgYTTKWtT1YgsE1XQiPQ1VV137n"
    "WTza9z4OHRpC3xNHoPmrkbUl1NSEIEu8SxCDIwBXeBBCBsiB5LlMsouAMGUfE9BUGQioyuxB"
    "dPit48dGhscebK6vQW0oiI6mWqxauQhlSUHWdUC2Lc1piGBeR+uqgfAq9PzTE1BvuBeVcgm6"
    "vwqLawWauA8jOb5TUxRUSgKCgTzPYVIlC5afRLmYh2MYcBwbhXwRXNEDZwHIElMx8evun05c"
    "XPj6x379dhBdg5B+7d9tXb9+2YqlmHQINdUyb2lpwPx4Z6fpSn91tKfnuZuut6AygZJh4OiQ"
    "AdPFjo7G6g2qqiNbsaEwDu4aHs0M8bNn+tIGSf9tQB+F8PqhhkagVw3eBkC68cHvILtwKbKv"
    "f7O8Z+rdk6+9dbEb7zz085plG7va5lR1BuqC5DZoGJx2CWWZNUeq1tXcckvbr3rLA6lcPi0g"
    "Lw/6tZ8uaAxuWz6/Cf1JQqoiIHGP+cyUSF3o4xMZ73vu4PEdofZrDlkL7joPnzoDu+QW+355"
    "+Wd0/69x94p6dHU1w8cZcsksDhw+/+f3rL/hBf+KNnHkVFnKT1ogBlRDQHfL0CSCX+VgngdN"
    "VsA1P3qnHQymLKiaRIwR+bIX+HT/8ZkL07ipvNM30vH94/j8yiXYPT0f2HMnAEACAPT+J4JL"
    "NyHgY4jWBuFTtfktc4Lvzb15AQ6dt3h23IQAEQRYwWEwmA5X0lF2NeRdH8ZKEk7GbMSKAqom"
    "kSRxJskSebLmVWskkVvcO7/amVh93zfwQe8UJl687+obEYOEmUQBk/0jYLr+4V1b1uLQqEBm"
    "2oHuk8C5DMv2PMciXjAczOQEWbZgrgCIgSRJYprGwWRGnHPIisShhoTw5vnrK8abPz421fCF"
    "FteBpACb9wKvbPodBwA889bLzA8fLiZyr2+4Z9XKIasKExcMhHSglpmojF9gPpkxWZUhiAMM"
    "TOYgRZGgccF8ZEF3MlArSUayyiBrUHwaFySTKnG9WChf/+Zzz/68HGqBwZuAMy9f6cC5GCFl"
    "lJHM5YcOn0qitllHg84gFzLo/egoBgaG0RBtqESiUb/euhjgQYAzBtcGN9KgxAgSiRhMy6lE"
    "Ohb6ldpmFIMNkOwK4+U0Srn0erH0T1c1Zk8eqY54GL2cd9aBD/rDSCfziKjegQj3wmXDWWnl"
    "0+h5Zz/6By8Wsq5vy8y5sW9DEuWq6qo1CNbC4xKYcD0pMcgGek8lxnLud7P56HcyZmpPIhr9"
    "cr1VCLLSDOJ9JzBTEj8LRpr31ky+V66JNGHqdPeV94HacA2Gnr8Hq5Z14N8eWvutgbOD3333"
    "rQ8wNJU5UQk03IbGZS91fLZzIhgIPMaEVSLhgCkKScz1rEoJFvPtk63MTxbVj53du2bqw+Ij"
    "yxtzk0MvTQycQ6ws/cxa8vD2YsWaOXN0P4j/33toFuBzX/wsar78Y/xo8+UOZdJTMzm3061b"
    "vA7V84+tarXQdU0r2pcuATwxTrYN8jww12KO44JkfSoSbUWAC6zvXw0AGP6voQfiGVpuB1t3"
    "8olfFCVNBwC4atXVAL/ZtgS5t7cDCIAxhmC4DkiePr9Mz8xIMPDRuANH1ZlrVuCDk1MKMaiJ"
    "IaabGUlYBizBxuO7vwWPcTj//CUAwIJH/xLB+OFPYCPj+WqhqhoA4JN/3Xr1NvxthLf8AJld"
    "G/He9lWIPPAKhkmHeOnylvnMB5TPF5DMmQ+RcfE4GAOTFZTKLmx/eAAAxrVrZrWGttWj9tQm"
    "+D0fKi/cjvL/T/b7ADK7Ns6OU/+x+cpJSUVtqAqHTiROwMlXQws0A8KDX1cRnDMMABkleqmC"
    "AMAYsr8n6R8F+KOh6ihVyoDEgHy8iBPHziN/BBuu78Abp0YurfGcTyX5v07J9BdogvzUAAAA"
    "AElFTkSuQmCC"
    )

# ---------------------------------------------------------------------
play_fig = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABkJJ"
    "REFUWIXFl1tsVNcVhr+1z5kZe8CEBlWghpJAIQTIBYPTkgJu2ki9PSC3KEOooqpq1Ieq7UMf"
    "mj70vVKjFKlSpT5VivJQt1MRpyEXNVLSBEgkwFGcQA0hMbfEUcAF23P1nMtefTiXOTNjRyqq"
    "lCNtz57x3vv/178uex34jB+5mU1HLgR3GiM7VFmLogJXQ/SdfRvc0/9XAi9dVr5zu/D8Fb9o"
    "1NxjhZ8K/DDdp9E6tdFcLagyhnLIKhMjm53as5MBI1vd/53AK58EPLTG5cXL9msY/ROwBQGJ"
    "d2gMjo3nCYHku+UDa/XxkS3u2CvvBzy0aXESpvuHI1PRybWK5F+4FB4So68ZwxbHAccBMdEu"
    "MZ1zJPO7AMJGEXnm2bN2tNJyigBj72o33NIKvHg5HHcddjouuMmhjsEPLaGCTayOLSdsz9VG"
    "ytj4U0M5az0Z+v4OaXwqgZenAxaqknf7eCPnMlRwoeCA4wgiMDVxjlUbvkhuYBleqIRZ2RcF"
    "jkmFglrOozK4ap3XGF5Z6HXBkSnlm7e5mAK/dR2GCg70u0IxLwzkYCAn3DEww5c+eoKPz1yg"
    "kDeYRPo4NiSZL2aecKeiTw2vLHD4bWWxJTw3ZYddo6/35WBZHpblhaILBRccESqXz7DJfZpW"
    "7UOevzRCbut36b9lABvaSIGwS5FOBeL/yw/2D8poD4Ej5/0+HHPKdbm7mI8sXp6HgRwsdwUj"
    "UJn5kDX9Y6idROcnuThV5IXa79j8wH1oaDOASxCIYuViqLJdC1RK2ySTBWK2oWwVBdFITlcg"
    "Z6BgoOhAId8P7gCSzyMrHDZsnOQnq3Zx/V9/oFFpRJvi4Eyf3vl6gw6VtklnDKjyGGCS/VYh"
    "VPAttCw0LXheC2wN1EMkRPIBfWtaHNj4S+5+/0GuvHMa45pI1yVIaIT1OEC5rBkFlB8Rp1do"
    "IbDQCmEhhGqgVHyoVucg+AjsDQgrQBNxFWc5bFr7Fo/138fsa0/SqNajgpBVo3P+LYBSKXbB"
    "c5N6m0K/EvkpsNDylWYANR+qPsz7MDd3Hfwp8KchnAW/CRYQRXLg3CKU1v2KXVceYPr0OFZM"
    "om6PGn87pV9OXRAKgwlDVfCDyPpGoNR9qHhQacF8ZRYWpsD7GPxZCFsQEg0FEcXJw9oVk/y4"
    "73504gm8Rj2KjUzJRsGx9v6UgFj7ebWSVjKbyO9D3VNqnlL3NXKBdwm8q+BVI+C46KRzQIzi"
    "5mHfil+z89JuaheOIXGApp5QVgFEN4SNqWT8pWEUgIEDJjKARqMOrbn2OgsELE7EQhjArSv6"
    "2X7Hat6rxTkfXVQJ14iAWjODKFiJ8sCSXi5q4z0CasMOyVOwsHOoL7SayrX1T3PWHKDeyCNo"
    "hwuA6ykBK7yd5J/GJCQOSFHQNL0lAvEzCnQBhy2lotu5eu9LnKuuBj9OrdjyxCACcyqNgf33"
    "yrRamu0y2q5cNnPJQAYwyAxfUA/qs8rs+md46/aTnKusjgpJtlegTby0R06mBCK/61NJZ0NM"
    "IvFlWkZJANtDPfAaSpVhLm6/wdHG96h7TlyDO2/JzFn/hO5CZOXParHZC8VaidWIRup3H9QH"
    "bcFCNcd/1v2DE2teZar6ORwUTVySvZg0k4bwJGQKURSc8m8sk91NRfZmgwRcCJvCtdZupndW"
    "OeHvo94yaKgdYKmiaX0HVS4alZPlN7WdBQD7d8hCeVx/Zqy+ntzx6UiJAy2YqTrkvvIyZ5oP"
    "Mv+JpBGe9oYZv6ffE1WR3xzYK5XkuFSB8rhSGpKjWP19t/XpZhVqy77N/N4mr17/OvMNEKs9"
    "69LPLnAshw/ukdHR40s0JIePBwQDTt4s6BsYhpIOOFm1eeUNrnm3MtcUUG2rkrTnGbkXUeG8"
    "eDLob/Iaj65rt2RLNqV/P2FPIQxlW6xQwcm4JQVO/nSDJ9bD+T6RwZE9vU1pT1teHo9PNbJb"
    "rf5RQ9IOxyQBmvktnXdHfdsNfxU/Ai8f623LewiUhuKXnmrolXY5vyCUb6hytjudujthusGV"
    "D1Tl4QPD5qAthg2A0t5ewT/11az8plL6qlA+pkV19B5Uf47Ko93rOlyAjqFyCJGJR4alNnpU"
    "OTi8NMxNvZz+5bjeZZQdYL9AiCJmRoWJg8Py7s2c95k+/wWLVxJCVyjU+wAAAABJRU5ErkJg"
    "gg=="
    )

# ---------------------------------------------------------------------
sort_and_filter = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABdRJ"
    "REFUWIW9lmtsVEUUx/8zc+/ebrfdLbRdkQpSqVXbaqBIUMEHrUYlgQs1FDQQX9RHYtQY+0WN"
    "+kGjMXwwaCK6iEb9VMG2PBrU4CNqBdHyMMXS1kAt0BZKaZfudm/3zhw/3Nu6fUFbgUlOZu7M"
    "nfP/nXNmdy4jIkymrdjsfcqn+9+O9Pc8Vvl47KtJOQHAJ7PJDBmF0wJXv7Fm0cuBoH/mRjNk"
    "5Fw2ADNk+L2Gr6r4xtXpe9orUJS/KjPJk7zDDBnGZQEQmthy39y105vDtejsa0FTTy2K8lZn"
    "c842XXKAks3eF+ZdU3Sr0vpEW7QRAHCitwFKszwFWYuWLt+UtOqSAZghY+41wZteuSXn/pQT"
    "kcPgTBtcO3TqG9xw1fxAekrWBjNkZF90ADNk+P3JadXmvKenHDtXh1Q9A5neWUgSKWBgUCTx"
    "28kqLL6hNOjRk3aaIcNzUQE0XXxZemt5VrvVgD4ZhiQJBoYUTzr8RiYMkYxIvBtNZ/fizmtX"
    "zmaMfXDRAEo+8T5fnP/QQq/X4F2xf6BIgSChyDEiQHAdOvegNVwPaOS5ftqCB8xNxor/DWCG"
    "jDmzMgpeLcxe7GuJ1EFBQZHtiA9AJMAwMOxv24X8rNsCU5Ov3GiGjJmTBjBDRqrPm7pt5YLn"
    "phyN/jYoTKSgSLljxxwABQCQKo49rZW4K3dVUBeeGjNkaGNpnBdA00XFmttfmt4ljyImzzmC"
    "cCIeLAEUpAuQ2MLWaTR37cPC2SU5AN6bMEDJJ95ni/NX3+5P8Yuz8eNO1JCDkStSbiYGMkBg"
    "YGCMgzEOzgSOnT0EXTOM3Mz5D5ohY+lYAGz4ZWSGjKSAL/102d1vpgimQUobkmxIZUNJG7aS"
    "kMqGrWxnTdmQMg5SBKUISjklIndsxfuwu/GLblv2Z1WXWdERmR4+0VEzu6DdMmLln79vAwQw"
    "AEACJYExENiQSTCQM0f/vc6Ys8B9WX9lFB0d9dodARA76V9n6PpUj0fn/+2goWoY8ZiwQCPe"
    "iXRYc3v+1CTKxgFgZJ9Zb+iiiOkqyMZQIScB56FwlgaSl54eDXtz2nwA+i8IMKeouSXsTfOt"
    "LS4PaJoO246DyK2tIpACSBEADkYcDMLpSYBBA4cAhwCDgC6SQJLw8a/lVqqF3tFARxxCAFj2"
    "kacwZ3rB7sU3m2n7uyqhlIKUEtJWkFJB2QRGOjhp4EoHgwZBOjjp4NAh4AGHjpumFeOX5q3h"
    "w221pVVlsa9HAxj1Z7jtif66ljMNb/3deiQ6yzd/JDUT4Iy75kTMmQBjAoJp4ExgZlo+2rqb"
    "rPr22s1jiY8JAABbH46+88vh6r3e/qAKaFcO3cScFHOmOaJcuFCO+Y1M+D0ZtKt+U4MRsF4c"
    "S+O8AABgU7Rk+77NbTm+O6BzY1Ccg0MMRs5dGAHBnLrnZixA5cF3O+OMllSsHPY3ORGAykeo"
    "O9x75oHvDlR25/nvBRGBgYO56WaMD6Z8oBx5mYvwc9OWcFek7ZHqxyInz+f/ggAAUPVE/97W"
    "rvr1x9ta+malFMJWFuIqBiLp1n3gLGi4KpCHU+FW6+CJHz6vWheruZDvcQEAwJaH+96sPbL9"
    "9wC7Wvk9V8BWFs7Fz6DHaodUcXAmEDCCmGpk0c5DHzb2nLCeH4/fcQMAAOze5TV/fNqeH7gH"
    "mnse4srC6egxdMfaMcOfj6r9GzqVspd8/xrZFx2g4nHq6op0rvypfmf3nIwlg/MEwnXpC/Fj"
    "w5fdHeHWdVvXRY+PO6iJAADAjrJ47bHOPzecOt3el+2fBwDIDhQifO6s9XfHwYrqsti2ifib"
    "MAAAVD4ae/3nI9UHgnouzUi9EdOT8/BTY3VzUMWemaivSQEQiKK9EXPXwc86cv2L8O2hL06F"
    "w3LZR09CMqdNyN+Qu8DdrSeYJ2GsJfRaQanIv+6elDeO7omur/s4vgeAAiAB2K7F3b7fHQ+Y"
    "ReR+QA4HcCE4ADEglGCJEANjDufmtV3xRCF7FFM0TPBfMgXIsAYHCVsAAAAASUVORK5CYII="
    )

# ---------------------------------------------------------------------
line_highligh = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAd5J"
    "REFUWIW91r1u1EAQwPH/kKvTEFFESsUjzEl5Bh4ke09DmWJd0tDwAHkDQMqKBprwkZQBgYKg"
    "oIKhuFtnb7P2+e7WHsmyvXPn+c36bm0xM9IQEQMwM2GCmOWFnXOTQmaxWD4TOWwsyCw9CSG0"
    "x977SSCzfKBpGpxzLWZsyANARACTQIoA5xxN00wCKQKmhBQB6Y9xbEgRoKqEECaB9N6CWpA+"
    "xKPSYF5QVYvjcdVMMRGcQ7YCdBXcBhL3OwHygnHfBYnny1sxqG4bG/8F3nuCCN7sQVequiy6"
    "yuczMyR6b4GqEkQIQBBppzrtPM3nM7UzAO47D4Az3xbx3qOqnfkqgLQzZ54QdK1IX74KIL34"
    "YrG87GIR1hBd+ToA7jtbG0867crvDXDO0ahjPi9PaOw0dr5vpO+E7erlvVsVKy8my04rAuJa"
    "HR8gQyFDQ0ROgTszuyoCYowIeQbciMgT4NbMPhUBI0LOgFvgLfBGRI6AH2b2sfdxXBFyBDwG"
    "joET4DXwQUQOegEVIQIcAIfAU+A38A34OghQAfIvOf4DfAGuge9bAYZCCiHAX+AGeAVcAD/N"
    "7HonwCZI4an4C3gPnAPvzOxzTOwF2ARJ3h9eAC/N7LL05eobYKvtOTDv++x/F8Pudw052iIA"
    "AAAASUVORK5CYII="
    )
