#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  30/8/2016                                          ###
#                                                            ###
# ##############################################################
'''


# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------
execute_bit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAwNJ"
    "REFUOI19k1tMVFcUhv99OefMdM7MwAQZlJo0jJYK3m3FaIFapWhiatIiITGEID6pMVWUxtRn"
    "FSRNvPSpsUSxliIvxsQUZ3wSlfoAInhBNKJyG50LpHFmzrD32X0pjU3B/3GtrG8l6/8XUUrh"
    "faqsqqCGYfTatgxwrl0539K6890+mQtQWVWxmXPeASDocrnKa+tq3GdO/ZTmnIeUUoXpdPqL"
    "9raOYT7HcCal9Nq3O77RRkdGtwcWBTSPx4MtW8t5IpEoI4TQrq5bnQDyZwUAmOQaHxLT0wVf"
    "btqozRTXfLqaAqCh4I0UFG4CwP8AlVUVmq7rfVDI82ZkAAA6/wgm7/fdV1u2lhvLli9lPp+P"
    "Symra2qrtX9v0HjyGAHgkFIODw4+yT7cUA8QwLIsNJ1otpVSe30+X+O+/Xs8ABCJRHHu51/C"
    "FACamo9XEUIsSulVr9fjcDgdOH3qLN68icAwDBQWFliMsdNriz5zAsBA/4Ddcq4lQQjpZ06X"
    "nkMI6Spat5Y7P3B+FFgUcJSUFKOnpxdZWVnIzp6HJQVLtJLSYpb7YS4DgO7uu9b42Hjrr62/"
    "VVIAYcbYsBACiz9eTL0ZXiRTSURjUZimC3dud2NiIgwAeDr0DAP9D9T8+X6DcVYGAJwx9pIx"
    "lukyXQCA3p57b1+HX7PS0hLtYusl5vf7Vd+9PlK3exd+b2tPc84fSSnzhBDbAYAyxjI3f7XJ"
    "ZZom0uk0xsfGdSHEIaXU2yM/fI/auhqSSqVw4ngTdF0PWZa1Sgjha2/r6AcALqWMBjtDdN36"
    "Iqfb7caC3AVWeCLcHAjkcUopXgy/EPmf5EtK6OX6Aw3V/7gtZmznUso8EDxPJpIL3W43Vq5a"
    "Yb6bi3h8cpqA/Fh/oOHobImjAPzKVn7GGZ4MDompqSkAwMjIqHr18pVtmqZOKd02R2LBgtdv"
    "/HXr9s2HY6NjX8dj8VAsFs/x5/iNP+/cTUUi0QexaIwKIco+31A8ORvgP9/YePKYkzH22Lbt"
    "XM75hYPfHd411+YZ/Q1klDP99knVqwAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------
help32x32_bit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABaVJ"
    "REFUWIXtlluIXlcVx39rn3O+28wkM5OMY9PYobbSYkoFRR0hGbRCL/jgpfpi9U2Q1triDREU"
    "BC2I1gcfRAz4YKnBeomiWGyJIok1DZViTNSmmtqkMU6nnZlvMtfv7L3W8uGcjE3ma5Iq4ksW"
    "/Dmwz957/ff/v/Ziw+W4HJfj/xzyShd8fu+jIyHL3tnutN+YhXClu+eIzJdl/Mva6upv7nvf"
    "zX/6nxD43I8f2dHudL6wedPQezYNDTQDTpAAgLmj7vSSMj/fPbK8tHy/qj74ldtvsf+awGd+"
    "8HBWNBpfHN0y+tmBVqNoFAVFlpNnAQkCSEVAjahKGSNlUmbn5g+urax+6Kvvv+WZ/5jApx56"
    "uNVstfaOjAzf1ixyms0GjSKnyHOyEMjCvxVIZsSklDFRxkivLFle7c0tdru33v+BW594uRzh"
    "5X7c++DPJOT5noGBgdsAJMsQCSABqYHIOkQCEgKSBQgBCRl5no+2Bgd/+Ynv/+K6V0wgZNk9"
    "7U77vQ4QAo5gdTIHGlng6sE2O4YHuHaoQyfPcKSCBFwEJJCFMJo3mw/d+72fF/3y5P0GP/7A"
    "T15VtFtfcjW8ENwFA8zBDEbaOTvHh2nlGSKCu/P64Q6PTXc5vpBwB/fKXZdAXjTeUMraXcA3"
    "LkmBkOV3YzZkgHtd5eaoGWbGW8c20cozjs4t8aPj0xyaWSAT4c1jm7F6nppjDji4GaEoPn33"
    "Az/dcOD+Fki4w8xwc8wMVUOTkZLSi4nfnp7j6OwZnpzpstgrOTa7SGlOp8jI3EjJarJewZ2Q"
    "Zdvd/O0XteDO7/zwahFe6/UGqkZQQ0TBHcuMZ7vKyYXl9Su0bbBNIwirSVlaK0lRUa1gptVB"
    "YiTk+U3AvgsSAHaYGgKoKqIJSZVQblmlSBJEBAGGWw1uumoMgN+dnGGtFysL1NBUk1ClUtRu"
    "uKgCgoxZigg5poqmhIhUXgbDtEoearzjuitp5xl/+Ocsv3/uBdRr5axaq0kxNUwVNx27KAF3"
    "M1OvqARFJJAQ3BwNgRACgiAC2zcPsG2ow6mFZR556iRRDXPH3OraUSwlTBOWFDfb0Jo3ElCd"
    "JmSYJ1SqZO5eVbJU7fcsgfHOKABPnJhmda2H49Vcr4tPFdOExoQnxfHpS1HgMIo7iIiQEDJ3"
    "3BwPVfcTqgbYDBW57vIKKUYc1gm4e21hXFeBIIc3Wt4nPvqtPYc9pRuzokHIC0KeEbK8arXr"
    "BIROo6DTyOmu9IhqOA7uVe+ws94nPEXMHfC3ffvODz5+QQVqHb7ral9XYq2K42pIyNYtQGAx"
    "JpZWqDev5lUcvK76hNcqSAhPORw6P1PfRuRmuyUL0xZLtCyxWGIpYimiMaIp4inxrhuv4ZM3"
    "T3LDFVuxGLGY0BTRVK+JkVSWuBru/uXdd93hl0Rg98c+vKQp3gNgMaJliZYRK8v1RJk7k9e+"
    "htHBNpPXbK/ufEpYrKCxIuspgfg+i+WefrmyfoM7p6akNzdzLGu2thTtgbe42TnF5fUVy7NA"
    "q8j59ZG/8vxcFz/bdFLCtYKl+OzM4UPvfvHPTy498/SxDQr0LcKpqakC2ITI1le/aed9g+NX"
    "3Y579SYI574FBOrioy5Aw6uuh2n5j1OPPfqRcnHhMNB197UDBw6cQ2KDAhMTEzI8PNwAtgDb"
    "lk6f/JtqudDZMn69qzaoN8et8tZ0/WuqteT4younHz91cN/X0uryGUCBFREpT5w4cWECCwsL"
    "TExMZFQ3JAO8Nz97/Mxzx38ViqLXGNx8BSIdr5uMm4JZ1TiCxNX55w/OHDn0zfmnj+511Vmg"
    "W2MRSOcT6GvBrl27gogUQLNGAyiAHJGiNbL1da2Rrdfnzfa4hKzQ2JsvF7t/X3lh+o8Wy8X6"
    "xLFGD1gDyv379+v5uS74KJ2cnJRGoyEvmXsW/dZ7n6+7u5/v+0vjX2tfsfjFkgQjAAAAAElF"
    "TkSuQmCC"
    )

# ---------------------------------------------------------------------
error_bit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAoBJ"
    "REFUOI11ks1LVFEYxn/nnHtn7p3xjqOL8QuRZiITxQoLE4xAiECMNu2tP6B1FNQyyD+gVYsg"
    "jGjXonQRkouswGyhfUjQxvyoURunwdE7957Twjsyab3wcF447/O8n4ID5joO3a6butzammv1"
    "vLQEVkulwsTGxrcvQbCVz+f/ircOClzP5YaGs9mrDY2NAwLSQmtMEBQGC4V3k8vLD+/m8y9r"
    "40XVudjWlrySzV4739FxT8XjibBSAWP2EIZYxqB9v/x6ff3WxObmgycLCyUAWRW4kMkM92cy"
    "NzEmEe7uIgApJUoIlBCYIEBo7fYnkzeGUqlLVZ4ESNt2qtfzbjvGtBrfR4QhUmuk1ihj9gAo"
    "rUkY09wbi93p6+pqqAqIHtc92eE4xyvFIv72NpVymaBcJtzZIfR9TBCA1nspSyXaK5Wjpzzv"
    "DCAsQGUd53QsCOzdeBw5NoZt2wgh9oEQGCHQgBoZIba4aLX39PQBUxYgJCSpVLASCTo6O3GV"
    "OrgcBBAAm7aNFQRYUAdIC2BN6+WwUDB6bU3sjI/jC4GM+pMRubqu2OoqVjzORiLxo3oHesl1"
    "P618/15sKBTqf46OYgGx6DMGewOMxGzgd0tL+W2xOA9oCeiPS0uLU2H4DKV8WUOwoteugXDd"
    "4FUmMzmzsDAPhBIwQOmFEI/n0+m5WE3JtS1UBeez2c9Pff8RUIy4++alPe/c/ba2iQ/19eur"
    "8Xi4qZQpKWW2HUevNDX9et7XN30sl7sIpA+dcuQnm1OpE4N1dQNnbXswJWWTpZTctaz8eyHe"
    "TG9tzXxdWZkDfgN6nzk7O1srZAH1wBGgG+gBckBDNIZD6/2fVUdAlE3/K+gPCjjsxxSH/qsA"
    "AAAASUVORK5CYII="
    )

# ---------------------------------------------------------------------
error_bit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAoBJ"
    "REFUOI11ks1LVFEYxn/nnHtn7p3xjqOL8QuRZiITxQoLE4xAiECMNu2tP6B1FNQyyD+gVYsg"
    "jGjXonQRkouswGyhfUjQxvyoURunwdE7957Twjsyab3wcF447/O8n4ID5joO3a6butzammv1"
    "vLQEVkulwsTGxrcvQbCVz+f/ircOClzP5YaGs9mrDY2NAwLSQmtMEBQGC4V3k8vLD+/m8y9r"
    "40XVudjWlrySzV4739FxT8XjibBSAWP2EIZYxqB9v/x6ff3WxObmgycLCyUAWRW4kMkM92cy"
    "NzEmEe7uIgApJUoIlBCYIEBo7fYnkzeGUqlLVZ4ESNt2qtfzbjvGtBrfR4QhUmuk1ihj9gAo"
    "rUkY09wbi93p6+pqqAqIHtc92eE4xyvFIv72NpVymaBcJtzZIfR9TBCA1nspSyXaK5Wjpzzv"
    "DCAsQGUd53QsCOzdeBw5NoZt2wgh9oEQGCHQgBoZIba4aLX39PQBUxYgJCSpVLASCTo6O3GV"
    "OrgcBBAAm7aNFQRYUAdIC2BN6+WwUDB6bU3sjI/jC4GM+pMRubqu2OoqVjzORiLxo3oHesl1"
    "P618/15sKBTqf46OYgGx6DMGewOMxGzgd0tL+W2xOA9oCeiPS0uLU2H4DKV8WUOwoteugXDd"
    "4FUmMzmzsDAPhBIwQOmFEI/n0+m5WE3JtS1UBeez2c9Pff8RUIy4++alPe/c/ba2iQ/19eur"
    "8Xi4qZQpKWW2HUevNDX9et7XN30sl7sIpA+dcuQnm1OpE4N1dQNnbXswJWWTpZTctaz8eyHe"
    "TG9tzXxdWZkDfgN6nzk7O1srZAH1wBGgG+gBckBDNIZD6/2fVUdAlE3/K+gPCjjsxxSH/qsA"
    "AAAASUVORK5CYII="
    )
