#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  27/8/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

inew = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfpJ"
    "REFUOI2lkj+IE0EUxn9vdzbostwVHsRWtAheY2GTCGmCaQ8sLOUKQZsgCioWcq2CpRxnKglY"
    "CBb+qSwTEMtUBjkCFunkGnHzZ3fn7Vgk2SRwV/lgYGa+ed/73nwP/jMEoNVq3a3Vaq9KpRLO"
    "uQJ0ztHtdo9Go9GLcrns1hPb7fYfAANgjLnUaDS2wzAkz3MWd4zHY6Ioejoaje4bY+YVRbDW"
    "MpvNnnU6nSMDkKj89ewMsT6S5xgPHj56wmAwWBbcPkX9Yb1eP5R6ve5OAQGoVquISNHWentJ"
    "kmT9fj8wAM1mE8/zUNViiQiqyng8RlVxzm0QTSaTFJgTxHGsQRD46wSqirUWVeW9vb6h7Jb7"
    "TpIkUnyi7/sYYxARRATP8zb2WDh5cweAnXsdjDEEQeAKAmttIXlZ1VqLtZYsy0BAk7RQkKYp"
    "aZquFKiqdc75y/7yPOfd7Nr8tSySsqwg+OjfgC1CthYEw+FQoygqfAbgPJy8vs1kmqF5TjxN"
    "APj1cg/f8whLPjsPPswJ5oXdhmUAdjplMs3InSO18wFz6uGJIOpTtJCmabCctCJCuPj4S3H8"
    "cXATgKsHXzeeLW0sxXG8Aez+frtKruzDmrLdnyvM9Hq9CvhXAJ8z4kJl/9O5YAX3et/2AAUd"
    "GuAY9Bg4c6QBLj9fl66fWfjzD4Xh/5kh9ImPAAAAAElFTkSuQmCC"
    )

iopen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYtJ"
    "REFUOI2lkb9LW1EUxz/n5eWZDMGiLfnRIU9sE+ySwa0FheAgdBA6iIX+Bd2yZRQKpXspDjr2"
    "P6mD4lCoWEhakaBoUiGkMRWam/eOQ/KaRKNB+oXL5Zzz/X753nPhPyEA00k3GXvw8H3Yibwa"
    "HLaa9ZdnR9+3xxo8zb34LCJrv+vnoWDgeYbJqbhB8EcJfa+zcXSwVxCAR49nq77vxe8TPexM"
    "lKuVUtYGSM9m7yXuIVOtlLABKoclQo4zhi9DldduA3QNJGQhYo3WqaIoqN8rlUDTN8BCRPoE"
    "Vbo0HQggvat7+x3TNwiG/wgi1wLfhC+dAQPAskK3kgG8jiGzvD7U+7WxmhKAhDunzkT0ToOZ"
    "fJGWN8nOpzwAi8UDwpflbgJLLMJO5E6Dyo8mqVzmRi+Ajjvu0pYaY9QYo6qqp42/6i5tqQ3I"
    "dNIdftwI2O2z9Tcfdnm78oznczEKH/e4qB1+C5YdZWChtyD3ZOHdl2xunoj/h+2d/Ubt6+br"
    "cb91HSnsRBqxI5iTn8DxFZX/iaWGn74XAAAAAElFTkSuQmCC"
    )

iclose = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZVJ"
    "REFUOI2lkjtPG1EQhb+5a9YPGYxMLMtQBEQCBQVF0qFUVChdKnqapOQfpPJfoI+iNCko8wfS"
    "RGkQEgEjBWMhxSsSjF+Avd57bwrjXVtKZB5HmmI0Z86c0Qw8EgIwU5gvTE4/KU64iTfDxXaz"
    "9rpa/vF1rMDz1bWPIrLZqP12BgWte2Sy+R6C+Vej0cFO+eD7tgDk5hY9Y3T+PtYn3PixVykt"
    "xwCeLi7fq/kWS16lRAyg8rOE47pj+DKSad8HQAGIoxAZCgTbbbLx0md9VRN0WmANWIM1Gms0"
    "4iiAvgNBIdKfYK3lunWJCpoU3+Wot2J8/vKH5JQhmc6EPBP0IgEksiciGL+BG0+xsytctq5I"
    "JFKYmxpqKhvyjATRCgBKOWG8XY9z8kmzf1TH89pUPgRsvYqPcESGVxBBqfAF2DtLEbTrHJ4k"
    "mE4bHAK+nWVHOAMBAZhdWLHJdCayp3tkdJXT8zpiLS+e5Sh38iCRwE27wa/yQbi8HXPD/0Fi"
    "gMwU5t8/pPuiehp+R5LBRe4OH+g+ZPAI/gLQd4jgpznLYQAAAABJRU5ErkJggg=="
    )

idelete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXJJ"
    "REFUOI2lkLtKA0EUhr8z2ayGxAuJEoJCIl5SWAi2KdTGxs7KJ7DSQgRbraztfAFbn8FGC7Hz"
    "EoggmiqBQFaNrLrJ7lgka6JGV/GHYTj8l/nnwD8hAIlUJtU3OLQbNnuXO8mnx+pS6TZ/HBgw"
    "OZM7EJGVh2ol5BOuW2cgnqwjeN2MntvYv7062xCA4ZHxsue5yb9UD5s91+ViIWsApMezfzK3"
    "MFUuFjAAijcFQqYZoJcPk+s4AM0ACSlEVHef1mg0aK81anxPOwCFiLQFWtOU6Y4C0rqat9eo"
    "twN88l0g8qnwV3jS6AgAlAp9K+4G/8uG/+pvAqafa6zyymgkwmn9iQulZgwAJYqw2fujOey8"
    "sCUOwxOTROJx5ioV4p675/M66CRBH6XT2rIsbdu2LpVKei+X0wYgiVRmJ6j+q/OSOFFqPba2"
    "xmB/P1XL4jKfv/OXHaFjod9hFrYXY7HNdDTKea12f2jbC0GeL8jAWBTm/fkNk1d8u3fkP98A"
    "AAAASUVORK5CYII="
    )

# ---------------------------------------------------------------------
iunhide = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAjxJ"
    "REFUOI2lkU1IlFEUhp/7zTfWjFmDQkIQBLUKAhfVptz1s4pqFRJDq0paaJsgDNxW5CJoI7io"
    "hRAGSSERUURYQYtCkDQnSctsxJ+YMR1nvnvuT4sZMX9aRAfezT2H5573PfCfpQDaR/zJoKgP"
    "oZQLquL59r3qxtrBtne/dlclk+e9c15BrGpLfKxtj+oMAbITs9eK+bkDAOHmaoBVgNZn43Wz"
    "cz8/F5YmAwWgApLbasvzAFpHYo0tTxtZt6Z2sYH8fC6IqQAUJGrr0l3Htr8HCADECNqWJWsA"
    "LS9/PJ+antlpnUVbQSVq7tw9Xt+93C8DtGBNWUZWAJf7Z65/GZs44r3FGkGF8Tf3T+1q+fOD"
    "EMCYCNFR2YErW7n0dPT0aCZz1TmPWCAWTj1u2te41l4lA0GsAcBXLHz9nu2NxBAohfOeVCqV"
    "XhfOsgVtIrQWtBaM8+XgCK4YMZV3TVxKHX8FGCNYG2FthMMB8OJCY4dKJB9YG+GdMJ7NNqQf"
    "DnZvCBCtEW0qWgnx1cXGM1bFh0UbvLV8yoyePfdoqHUDCytn1GvOuDD9bb94tyTWYKwwNDR8"
    "O907eHgVoBBJUIo0pUhTLOlVgI83m4tWSg2LJSHSwmKxyPBI5vWJe/07AMKuzs6wv5B/O+t8"
    "bQCbwqCg23t6jlYnEnEPeOcwSwv6Q87dGph3TcorcW5RV+dMO9Cs+vr6DsacaQRfj/dbnacm"
    "ciScc6nKEkopJB4EuTDAKMih1DyoSRcLn2x0mX+q3+yOT31vsT6iAAAAAElFTkSuQmCC"
    )

ihide = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkJJ"
    "REFUOI2lkU1IlFEUhp97Z+abUfy3rIhomxBBvwQhtIoICdoESQsrgrCgRcs25sJFizbRxgoE"
    "dxkkmkRZm3ATFFFqSZk/mS6KRMdR57v3nntbjJLKbKID7+rc85yHc+E/SwG0j4eLJmv3BBCl"
    "tPZeOtv2pz9vftw2Gm74FbsVgiYTvW2tV48UQHPv1F5r8kN4IQClmTQ11ZU7bzdsmV0PaH46"
    "E+zyAgCZsurRh6d21GuAztO7h1NllWdEBO+E7GKO+fns+80GzsWIE8QJ1hkLoNeanSe396TK"
    "q9qNWJwXfv6eq2t5/n1wPcA6i5HVOMMGAEBX466bOl0yIM4SgjA1PXPs+qvZu38NLLIaUxDY"
    "CAB4fLb+hPN+ypoYL5avY9+uXX0xeR4gv7SINTHWxLhiBmuVLsmci53FiSN2homJyS6AOL+M"
    "FVeIKxgkiwFKEv7OL2PQqsBXiagVQHzAiwMgJOPiBs29Ix1jk9NHg7eIxBCl+19eabgF4BWI"
    "xIjEuGIGF3pHLw0Pj1xWCqzxqFQ0PthyvHGtb61FTMHAJzcBmrrfHRwZGXpgRVBKgdLG57IH"
    "1i8wziKyOrh6xCTAyXvPar+MT73JLa2glMIFRWkmOvShtWlhPWA5HxNMYVCpVAIgeb+jI/l6"
    "ZaEtmJWJuhKV8iFE+6p09+GauC7qeXJK6QQKMHE+7hrLfTRaVQTIV0S5gU+A6uvrO5LwrgHC"
    "NkKoCFDuPJH1vjaEwjLAaq2zaY3RijmUWgD9wycS/cV+8Z/qD9EZPn1EjvDUAAAAAElFTkSu"
    "QmCC"
    )
