#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  27/8/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

explorer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAO9J"
    "REFUOI1jYGRiZhA3iv2//dKT/zCakYmZgVjMwsDAwDAp+BqDq440w9MzixjWtpswMDAwMNRM"
    "3vmfAQ38/fOH4ffvvwx/fv9mYGBgYPjz+w/EAGygJdedEZccMmBhYGBgePKJjeEvVODJJzZi"
    "9KEa8PEXC0NrsR2yEPEAOUCyG1aiBCAxgcuEz3DkwP202R+3F5BBVt0ypNDvwtBQ0rXpP95Y"
    "mNYUBQ99pVKz/+iB21PmhxI7eEOMmMDFa0DzxGME0wLeQBQziPq/7cLD/zCaZAPoEgt4c1pv"
    "ueX/n//+///57///3nJLrAmJ4lgAACWjf/lf+gFyAAAAAElFTkSuQmCC"
    )

# ---------------------------------------------------------------------

iopened = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAO1J"
    "REFUOI2lk71KA0EUhb9zsbC0FUUfQaxsrMTXEGKXd0jjI6SJdcA6vUUgjfgGio0QSJnCSOrc"
    "Y5FdXYJJdtkDF4YZ7vm5MyPbtEG06gYE3EbEdXUzM/u2F/UYpKUkVysiHmxTpyTpvyF8S+pv"
    "E83MF9tjgIONMwOvkiaZuWu6F8C4SPDnwHYPeAS6EXG4L35mflLJ/gEcS5ptzmRHTX+v0fYQ"
    "uANO9ymXkDQqHayAE0nvDdQNXJYEz8BVk2ZJb7YJYGl7GBGdutaLyE/l+gY4kvTVQD2BM9uo"
    "eE3nEXFfVz0z57YHwJqgDVr/xh/IxqHzCxAXfgAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------
iclose = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZVJ"
    "REFUOI2lkjtPG1EQhb+5a9YPGYxMLMtQBEQCBQVF0qFUVChdKnqapOQfpPJfoI+iNCko8wfS"
    "RGkQEgEjBWMhxSsSjF+Avd57bwrjXVtKZB5HmmI0Z86c0Qw8EgIwU5gvTE4/KU64iTfDxXaz"
    "9rpa/vF1rMDz1bWPIrLZqP12BgWte2Sy+R6C+Vej0cFO+eD7tgDk5hY9Y3T+PtYn3PixVykt"
    "xwCeLi7fq/kWS16lRAyg8rOE47pj+DKSad8HQAGIoxAZCgTbbbLx0md9VRN0WmANWIM1Gms0"
    "4iiAvgNBIdKfYK3lunWJCpoU3+Wot2J8/vKH5JQhmc6EPBP0IgEksiciGL+BG0+xsytctq5I"
    "JFKYmxpqKhvyjATRCgBKOWG8XY9z8kmzf1TH89pUPgRsvYqPcESGVxBBqfAF2DtLEbTrHJ4k"
    "mE4bHAK+nWVHOAMBAZhdWLHJdCayp3tkdJXT8zpiLS+e5Sh38iCRwE27wa/yQbi8HXPD/0Fi"
    "gMwU5t8/pPuiehp+R5LBRe4OH+g+ZPAI/gLQd4jgpznLYQAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------
iopen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYtJ"
    "REFUOI2lkb9LW1EUxz/n5eWZDMGiLfnRIU9sE+ySwa0FheAgdBA6iIX+Bd2yZRQKpXspDjr2"
    "P6mD4lCoWEhakaBoUiGkMRWam/eOQ/KaRKNB+oXL5Zzz/X753nPhPyEA00k3GXvw8H3Yibwa"
    "HLaa9ZdnR9+3xxo8zb34LCJrv+vnoWDgeYbJqbhB8EcJfa+zcXSwVxCAR49nq77vxe8TPexM"
    "lKuVUtYGSM9m7yXuIVOtlLABKoclQo4zhi9DldduA3QNJGQhYo3WqaIoqN8rlUDTN8BCRPoE"
    "Vbo0HQggvat7+x3TNwiG/wgi1wLfhC+dAQPAskK3kgG8jiGzvD7U+7WxmhKAhDunzkT0ToOZ"
    "fJGWN8nOpzwAi8UDwpflbgJLLMJO5E6Dyo8mqVzmRi+Ajjvu0pYaY9QYo6qqp42/6i5tqQ3I"
    "dNIdftwI2O2z9Tcfdnm78oznczEKH/e4qB1+C5YdZWChtyD3ZOHdl2xunoj/h+2d/Ubt6+br"
    "cb91HSnsRBqxI5iTn8DxFZX/iaWGn74XAAAAAElFTkSuQmCC"
    )

# ---------------------------------------------------------------------
iview_package_close = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAOJJ"
    "REFUOI2tkTuOhDAQRB+yEblFAFcgIOM6nA0RcBiQCDkCEHAAEAJvsIIdf9BqZrcj66lcXd0d"
    "VFWl+UNJgLIs0fo9nyAIqOv620BrzTRNzPPMtm0ARFFEkiQAXp6m6U8CgHEcybLM6DIMA4CX"
    "Owbrujoxfczm9wjneTpCH7v4tbM7gZTSEfqYze+XUoq+79n3HYAwDInjGOCRGyMcx2GMcjF7"
    "xFetkWBZFoqiMKJ2XQfwyA2D686v5WM2/78rCCEcoY/Z3LhC27b34oQQKKUAHrlhkOe5t9tv"
    "JQGapvnoM8AXr2+Whh5hxpAAAAAASUVORK5CYII="
    )

# ---------------------------------------------------------------------
iview_package_open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAANVJ"
    "REFUOI3t0j1qAlEYheH3Xr9vEKu0ps8iXIHVMIW4CHfgNBYGXEFwB6YTtBYbV2ExrSAGptDh"
    "zp0BM6n86W6RMjntA6c4HGOAwWQSA688sl1OpxkBA8AASZqOznXdHC6XZr3bNUmajpLx+C1k"
    "BrAAtfet7+uVynuKomA1m83rquqHjFuB976lInSiiDzP+VgsyPb7l5ABCIB3TtRa2qoM4xhR"
    "5XOzKbOA3QtK50SspRNFqAjGWkrngnYv+DoeT91e7/1paUT1FDIAY/hdBP5/AH/+Bz9mZw8S"
    "5wDYvAAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------
iview_pack = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAJpJ"
    "REFUOI1jKD364T8lgImBQsCCS+K2mhxBzaq3HjEwwLzAMMke7qxbqrJEe4EBOQwYJtmTpBkj"
    "DG5NvseglqtEWiDAXIBsM7J3SPICigSSIQw1h3HK4zQApgimGdkQFMPxGlBzGMMl6N7D7QUs"
    "NiK7CK8B+PyMYTi6Adg043MhakIiUjMyQElI/5ttSEtEDNDMVHbsI8kaYQAAGyOJrJPnBOgA"
    "AAAASUVORK5CYII="
    )
