#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  1/9/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

# ----------------------------------------------------------------------
smiles = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAolJ"
    "REFUOI1tk91Lk2EYxn/vx7OmwyBhVsytmY1cCBFBQWSRlYVGJ51EjajptliH4X/QQeJ5J+ZJ"
    "f0AnIVSWJ0EQQfQhzNG3JkRQILrl3tft6sDNRvnAdfI8z8V939d13Vi2w79IpS4pHt8p17Vk"
    "jK1EIqpcLqPN/to0nWwmrc5IUL29n3jw4Ajl8mVKpYvcv7+frq5HdEZqymauqZljWbYDwOlT"
    "xxSL/eTOnfMY4wElYAWoAhXgI75fIJ/3mJ8/wvST5xaw3kE2k1YsBhMTtzEmCYTqxEaxVaCM"
    "MRYTE1uIxZ6RzVxdf7Rsh2i0XZ5XkPRF0mONjo4KkJSSlBKgcDgsqVVSizwPRTuRZTu42Uxa"
    "XV1rGNMCOECN8fHxpimX6OnpYW5uDmgF1TAEuXG9yuf5lOyZmYcMDUWAReAj8LqJXAEWWVhY"
    "aLqrQaWVoZNtzMxMYRljq1S6iTFtwCrDw9+ZnPQ2hIOFuqB1crUKSx34qw6hXfMNG7264stM"
    "TvrAEvAOKDaRBVpjd2cQ/BbwgwDY8XiEYvEb8AMokky+BF7UK+svGR+qNp+/L0O5jeKcRXxX"
    "GLe//wxTU/fo7Q0AolCAUEiUGoWpAWtQtTi4rw19iUB5K1OPf9F//GTDRkue11K3ad0qBYMK"
    "BAJyXUehoKv93e3S4l6p0Cfv1QlFdwS0EeXBwTT5/Op6mw389qn4Pr5jcTjZweunUVgOw1qA"
    "/K0ig2fOsREky3YYGOjTyAjyPCTVUbWllW3St6T04ZC8N0c1cmGHBo4f0H/LNP3kueU4w3R3"
    "w9gYzM6CX3HwKzaz71cYu/uV7rMvcLb2Mf3srbURi81WNJdLK5HYLuMi46LEng7lMlc2Xec/"
    "xiMt8QU2mDwAAAAASUVORK5CYII=")

# ----------------------------------------------------------------------
small_up_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUOI1jZGRiZqAEMFGke2gY8P/f3/9kGwDTjM8QnAaga8JlCG3CAJdt2MQxDCAUaOjyjKMp"
    "cRAYAABS2CPsss3BWQAAAABJRU5ErkJggg==")

# ----------------------------------------------------------------------
small_dn_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEhJ"
    "REFUOI1jZGRiZqAEMFGke9QABgYGBgYWdIH///7+J6SJkYmZEacLkCUJacZqAD5DsInTLhDR"
    "bcPlKrwugGnCFy6Mo3mBAQChDgRlP4RC7wAAAABJRU5ErkJggg==")

run_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAPhJ"
    "REFUOI1jYBgFjNgEsxebf/315xfXr39/uBYmX/6OzwAmbII//vxikBHRZPjx+/c3/6nynCQb"
    "wMPGw6UpYc4gK6zO8O3Xjy+23YI8JBnw598vhmcfHzPoylgzKIvpM/348+2jbjMjP0le+Pb3"
    "O8PDd3cZDGRtGdQlTZl+/Pn/lgQDfjD8//ufQZRXmuHc46MMR+8eef3tF4MJNrUs2AS//fnB"
    "IMgtxnD64RGGvbd2vfj1h8H5eTvDNWxqmbEKWnws+/+fmXX/zT1Pf/1lcHreznADmzoGBhzp"
    "QLGW4evff8xc3//9VXrdznAfl2a8QLicAW/8Dx4AAHR1YeN2C0QUAAAAAElFTkSuQmCC")

refresh_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALNJ"
    "REFUOI2lk7ENwyAQRR/EUopUtBRRRrHEAh7E43gQFkDyKFEKt65SkyZEGLBNxK/Qcf/r7t+d"
    "8N57GiBbyABdGtBjnyUt01wnoMceMygAnF0zYhCP4zL+PCObQWEGtamyyoNYHNiInAqERGfX"
    "Xyy89djnJqYIraTmhnhXcj0mHE0AQIaEtMcaMnw9WKYZZ1eu8gKUp7AHEa/yXtlHIxalW3i9"
    "n9xvj6qtLAr8g+Zjahb4AEW6VPXp5dKQAAAAAElFTkSuQmCC")

my_bitmap = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAA3NCSVQICAjb4U/gAAACc0lE"
    "QVRIiaWW223sMAxEj4LtiC4htXBLSC1yTVJNvB80aVmWNxcIYRiOIs4MH6K2mBl/sFLKZ4Sv"
    "/0TJ97i4XJkWfyFIh3RLlAZAys9Q2iTFng2wqqZi0MBUgOrfz76ADv/9hSDNQZ3sszKu9It9"
    "I641UagOHaGMybk72rDhQnCCRloujx6eNR6eaeoTgVW1CHCydv3zTnOCqFxW1pkJXR6yE18C"
    "j2pPHFMBbhHcPwb0OnnGoo6aVBrIhyLn1ixXapzQFVqVFqH4il0pFwQpvK1wT+2CgTV1Dgvt"
    "DTQed1ycZDMrsLEuT9pxWN99gwJl78AGovTIEvBiONlncp7nVymlCVunVWHbHUsVOnunKiIC"
    "Pfd/MXTLNKcm20oppShsHWvKu++wgzqoAIhI751lBCU4RvnbQNmhVRER7Z1tz3URAfYdVcbN"
    "ktkYa5s9IyDQqljTGvXMSefNI1CVVqXqsblVEfBOXXSRQ7unNXXolpOuHmMje9fRHbQq1g6m"
    "x1Hhq67lEBug/tGGCeHoCZpMjyc57ZDPCX2fcaO5fOeT+4G/o4/y2+0wT5UbO+Iuf0GA1zPy"
    "Xm+KbDWfD2XLzXcCiSdL+qR9Cv2Obmav0XkrRaCpIELvANJ5U+Ede+6/U/wYCQ82qTjunOGC"
    "HOu8tBqNLzHjRtjXvL13YN/7RdEbAVHkPL+H5B7vnmdzCnSKQCLvGhX25E4HwjQaTE/VqSlv"
    "iMci5yQ4h0G45VOHyXNmOEDqnUBCRcYxzqWk8feyitN3E/BrI7Np3j9eib0DO7z9Cvo4ybOv"
    "xh47XCwvd5UaBcjZMP1KXEJ/tk+6/mg/Pz/f39//AMddM+4FSbimAAAAAElFTkSuQmCC"
    )
